/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef HIGGSWIDTHPDF
#define HIGGSWIDTHPDF
#include "RooAbsPdf.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooRealVar.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TH3F.h"
#include "TH1.h"
#include "RooDataHist.h"
#include "RooHistFunc.h"
using namespace RooFit;


class HiggsWidth : public RooAbsPdf {
protected:
 
 RooRealProxy _GoverGSM ;
 RooListProxy _coefList ;  //  List of funcficients
 TIterator* _coefIter ;    //! Iterator over funcficient lis
 Double_t evaluate() const ;
public:
 HiggsWidth() {} ;
 HiggsWidth(const char *name, const char *title,
                      RooAbsReal& GoverGSM,
                      const RooArgList& inCoefList);
 
 HiggsWidth(const HiggsWidth& other, const char* name=0) ;
 virtual TObject* clone(const char* newname) const { return new HiggsWidth(*this,newname); }
 inline virtual ~HiggsWidth() {}
 
 Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
 Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
 const RooArgList& coefList() const { return _coefList ; }
 
private:
 
 ClassDef(HiggsWidth,1) // Your description goes here...
};

#endif





